### ISSUE TITLE
Vertical instead of horizontal

### ISSUE THREAD

**Issue by huy1741** [hungga1711/react-native-dnd-board#1]
Hi,
Is it possible to switch the views to vertical instead of horizontal?

**Comment by baronha** [comment]
> Hi,
> Is it possible to switch the views to vertical instead of horizontal?

Yes, Of course!

**Comment by hungga1711** [comment]
Vertical board is not fully supported yet, but you can try to set horizontal={false} in props.
`<Board
  ...
horizontal={false}
/>`

**Comment by baronha** [comment]
> Vertical board is not fully supported yet, but you can try to set horizontal={false} in props.
> `<Board ... horizontal={false} />`

Oh no, bro. I wanna vertical. but I am a newbie. I cannot folk this repo to improve. I need you, bro!

**Comment by hungga1711** [comment]
@baronha It has been implemented since v0.0.6 (current version).

**Comment by baronha** [comment]
> @baronha It has been implemented since v0.0.6 (current version).

Wow. Thanks, bro! I love this lib.
