### ISSUE TITLE
Render Row Card Based on a Specific Column 

### ISSUE THREAD

**Issue by AbdullahQureshi1080** [hungga1711/react-native-dnd-board#5]
Is there a way we could render different row cards based on the column,  Column A renders row card A, Column B renders row card B and so on. Help would be appreciated.

**Comment by hungga1711** [comment]
Currently, I think the only way is set columnId into row data and use it for conditional render.

**Comment by AbdullahQureshi1080** [comment]
Yes, figured that out. Done. Thanks. Great Library. keep up the good work.
