### ISSUE TITLE
Delete Item from a specific column

### ISSUE THREAD

**Issue by AbdullahQureshi1080** [hungga1711/react-native-dnd-board#7]
I have two columns Column A's state need to be preserved and we can move items from column A to column B by adding new rows to column B copying the data we get on drag from column A. The Issue is the while deleting a card from column B the card get deleted from column A also. 

Tried to reconfigure the delete row function and provide column id two only so the card gets deleted from second column only having usual behavior sometimes it gets deleted, sometime the last element is deleted.  

It could be my approach on deleting is wrong or I would have something wrong altogether, help would be appreciated. 

here columnId = 2 so it gets deleted from column 2 only. 

```
deleteRow = (rowId, columnID) => {
    console.log('The Row Id', rowId);
    console.log('The Column Id', columnID);
    // Manual find index to optimize loop time
    let rowIndex = -1;
    let columnId = columnID;
    // let columnId = '';


    const columnIndex = Object.values(this.columns).findIndex(column => {
      const i = column.rows.findIndex(row => row.id === rowId);
      if (i > -1) {
        console.log('The row index', i);
        // columnId = column.id;
        rowIndex = i;
        return true;
      } else {
        return false;
      }
    });
 
    console.log('Column Index', columnIndex);
    // // console.log('The current rows :', this.columns[2].rows);
    if (columnIndex > -1 && columnId) {
      this.columns[columnId].rows.splice(rowIndex, 1);
      this.originalData[columnId].rows.splice(rowIndex, 1);

      if (Utils.isFunction(this.reload)) {
        this.reload();
      }
    }
  };
```

**Comment by hungga1711** [comment]
I think your rowId was duplicated.

**Comment by AbdullahQureshi1080** [comment]
Yes, Solved. Thanks. I used the same id that was returned from on drag to the new card. 

Though the indexes do not change on that instance when a card is deleted re-arranging get the indexes to update any advice on how to get them changed on deleting?

**Comment by hungga1711** [comment]
You can use `getItemsChanged` function. 
`const { columns, rows } = repository.getItemsChanged();`

**Comment by AbdullahQureshi1080** [comment]
Yes, this return the updated rows. Thanks a bunch.
